engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
    - test/
    - lib/log.js
    config:
      languages:
        javascript:
          mass_threshold: 50
ratings:
  paths:
  - index.js
  - lib/**
